### ISSUE TITLE
WIP elfinder volume driver

### ISSUE THREAD

**Issue by sjopet** [symfony-cmf/MediaBundle#28]
I added a new branch 'elfinder' with the work on the volume driver I did so far.
Most basic functions like creating folders, uploading files, removing, moving, copy, download etc work. But because there is a lot to do still I figured it would be easier to add a branch then to do a pr.

Among the things that don't yet work are previewing, cropping/resizing and opening files in the browser. But I felt I got to a point people could try it out, review code and discuss design issues.

to run the code you have to:
- checkout the media-bundle elfinder branch
- php composer.phar require helios-ag/fm-elfinder-bundle dev-master --prefer-source
- follow installation for FMElfinderBundle: https://github.com/helios-ag/FMElfinderBundle#step-2-enable-the-bundle
- add the following to you config.yml

``` yaml
fm_elfinder:
    locale: %locale%
    editor: simple
    connector:
        roots:      
            media:
                driver: cmf_media.adapter.elfinder.phpcr_driver
                path: /cms/media
                upload_allow: ['all']
                upload_max_size: 2M
```
- navigate to http://you_sandbox_domain/app_dev.php/elfinder
